# arxivの学問領域の指定
subject: 'cat:hep-th OR cat:hep-lat'

# 検索キーワード
keywords:
        sign problem: 2
        complex Langevin: 1
        Lefschetz thimble: 1
        tensor renormalization group: 1

# 通知の閾値
score_threshold: 1
